import { FaUser } from 'react-icons/fa'
import { ToastContainer, toast } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { useState, useEffect, useContext } from 'react'
import Link from 'next/link'
//import Layout from '@/components/Layout'
import AuthContext from '@/context/AuthContext'
import styles from '@/styles/AuthForm.module.css'
import Head from 'next/head'
import Image from 'next/image'
import { FaSignInAlt, FaSignOutAlt } from 'react-icons/fa'

//import styles from '../styles/Home.module.css'



export default function LoginPage() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const { login, error } = useContext(AuthContext)

  useEffect(() => error && toast.error(error))

  const handleSubmit = (e) => {
    e.preventDefault()
    login({ email, password })
  }

  return (
    <div>
      <header className={styles.header}>
        <div className={styles.hone}> <Image src="/images/site/rangeimage.png" alt="image of range logo" width={180} height={185} /></div>
        <div className={styles.htwo}>
          <Image src="/images/site/rangeimageheader.png" alt="image of range address" width={400} height={180} /></div>
        <div className={styles.hthree}><Image src="/images/site/rangeimageaddress.png" alt="image of range address" width={280} height={180} /></div>
      </header>
      <hr className={styles.line}></hr>
      <div className={styles.grid2}>
        <div className={styles.boxone}>
          <div className={styles.auth}>
            <h1>
              <FaUser /> Log In
        </h1>

            <form onSubmit={handleSubmit}>
              <div>
                <label htmlFor='email'>Email Address</label>
                <input
                  type='email'
                  id='email'
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
              <div>
                <label htmlFor='password'>Password</label>
                <input
                  type='password'
                  id='password'
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                />
              </div>

              <input type='submit' value='Sign In' className={styles.signIn} />
            </form>


          </div>
        </div>
        <div className={styles.boxtwo}>
          <h4>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Enim, eaque ea vel eveniet facere similique, sed laudantium possimus labore eligendi accusamus quidem dignissimos alias in! Totam possimus quae doloremque, provident iure error, culpa beatae commodi laborum, illo explicabo esse. Sint.</h4>
        </div>


      </div>


    </div>
  )
}
















/*import Head from 'next/head'
import Image from 'next/image'
import { FaSignInAlt, FaSignOutAlt } from 'react-icons/fa'
import { useContext } from 'react'
import Link from 'next/link'
import styles from '../styles/Home.module.css'




export default function Home() {
  return (
    <div>
      <Head>
        <title> Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid2}>
        <div className={styles.boxone}>
          <Link href='/account/login'>
            <a className='btn-secondary btn-icon'>
              <FaSignInAlt /> Login
                  </a>
          </Link>
        </div>
        <div className={styles.boxtwo}>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Enim, eaque ea vel eveniet facere similique, sed laudantium possimus labore eligendi accusamus quidem dignissimos alias in! Totam possimus quae doloremque, provident iure error, culpa beatae commodi laborum, illo explicabo esse. Sint.</p>
        </div>


      </div>
    </div>
  )
}
*/